ignores:
  - '@oclif/plugin-help'
  - oclif
  - '@commitlint/config-conventional'
  - declapract-typescript-ehmpathy
  - husky
  - test-fns
  - rhachet
  - declapract
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - tsx
  - simple-lambda-client
  - "@src/*"
  - "@src/.*"
  - tsc-alias
  - yalc
